### ISSUE TITLE
[BUG] Stats - Matches chart 

### ISSUE THREAD

**Issue by geocacher1** [akasolace/HO#1561]
**Describe the bug**
I don't know if it's exactly a bug or just a feature which I don't understand. On matches statistic page the X axis units on a chart seems to have weird format.

On every other chart in other tabs there (players, team, club, finances) the X axis units are days. On matches chart the X axis units are in time format. 

Is it a "bug" or I just don't understand what data are displayed on the chart? 

My club is just about 2 weeks old so data sample is quite low. There is also weird X axis units while its no data (e.g. when i choose my cup matches, while i haven't played any cup game)

Screenshots below, i can provide more info if needed (just need to know what more should i check/write about it)

**To Reproduce**
1. Go to 'Statistics'
2. Click on 'Matches tab'
3. See error

**Screenshots**
![No data chart](https://user-images.githubusercontent.com/108490960/177004348-59f04790-ca0e-4989-8832-e07bb04c0c69.JPG)
Screen 2:

![xaxis bug](https://user-images.githubusercontent.com/108490960/177004351-ab194e63-8939-4128-a57e-d70c60d34eb8.JPG)

**Platform information:**
 - OS: Windows
 - Version HO 6.0 BETA r329

**Additional context**

**Comment by wsbrenk** [comment]
time format in match statistics were an error - should be fixed with the commited changes.

-1 .. 1 is because the diagram is empty

**Comment by geocacher1** [comment]
I checked it. This kind of bug still exists and needs more tests. The output data is changing depending on the weeks chosen. in my situation (club has been founded 11.06.2022, first match 12.06.2022):

- **Finances tab**: when i choose 6 or less weeks, X axis units are in time format, for 7+ weeks there are as they should in date format. 

![finances tab](https://user-images.githubusercontent.com/108490960/177016935-859c54d2-3689-4158-a5f9-74aa4d19b3fb.JPG)


-  **Matches tab:** I chose, 2 weeks period, and i got a week in the future (?):

![2 tygodnie](https://user-images.githubusercontent.com/108490960/177016867-59a29cc8-63cf-4771-967d-049e2686f8ab.JPG)

When i chose 4 weeks the time period on X axis is longer, but still not correct:

![4 weeks](https://user-images.githubusercontent.com/108490960/177016869-775d5550-19db-42e4-a6cc-ea911ed6e8d0.JPG)

When I chose 50 (default) it looks ok, but still shows some future dates with rating value = 1. Maybe that's because i have quite 'young' club. Can someone else check it?

At least for me, in almost every tab, the chart is not showing a period chosen (when i chose 3 weeks, the chart showed data starting from 18th June, so last 14 days)

**Comment by geocacher1** [comment]
Hi ! I tested this issue after updating to Build 336. And the problem on Matches tab seems to bo solved. But on Finances tab there is still sth wrong (when I choose e.g. 4 weeks period, it shows on X axis time from Saturday 14:00 till Monday 18:000)

**Comment by geocacher1** [comment]
I was busy, so i had no time to check it earlier, but it looks ok now (on 338 build). I tested it on every tab, changing weeks period and it's fixed.

**Comment by wsbrenk** [comment]
thanks
