### ISSUE TITLE
[eBUG]ArrayIndexOutOfBounds at HO start

### ISSUE THREAD

**Issue by wsbrenk** [akasolace/HO#401]
ArrayIndexOutOfBounds starting HO 3.0 r2644 :
java.lang.ArrayIndexOutOfBoundsException: 30
	at core.gui.comp.table.TableSorter.getValueAt(TableSorter.java:155)
	at core.gui.model.ReduzedTableModel.getValueAt(ReduzedTableModel.java:56)
	at javax.swing.JTable.getValueAt(Unknown Source)
	at javax.swing.JTable.prepareRenderer(Unknown Source)
	at javax.swing.plaf.synth.SynthTableUI.paintCell(Unknown Source)
	at javax.swing.plaf.synth.SynthTableUI.paintCells(Unknown Source)
	at javax.swing.plaf.synth.SynthTableUI.paint(Unknown Source)
	at javax.swing.plaf.synth.SynthTableUI.update(Unknown Source)
	at javax.swing.JComponent.paintComponent(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JComponent.paintChildren(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JViewport.paint(Unknown Source)
	at javax.swing.JComponent.paintChildren(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JComponent.paintChildren(Unknown Source)
	at javax.swing.JSplitPane.paintChildren(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JComponent.paintChildren(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JComponent.paintToOffscreen(Unknown Source)
	at javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(Unknown Source)
	at javax.swing.RepaintManager$PaintManager.paint(Unknown Source)
	at javax.swing.RepaintManager.paint(Unknown Source)
	at javax.swing.JComponent._paintImmediately(Unknown Source)
	at javax.swing.JComponent.paintImmediately(Unknown Source)
	at javax.swing.RepaintManager$4.run(Unknown Source)
	at javax.swing.RepaintManager$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)
	at javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)
	at javax.swing.RepaintManager.prePaintDirtyRegions(Unknown Source)
	at javax.swing.RepaintManager.access$1200(Unknown Source)
	at javax.swing.RepaintManager$ProcessingRunnable.run(Unknown Source)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

HO 3.0 r2644.

**Comment by akasolace** [comment]
@wsbrenk do you have more info about this one? How is it produced?  Is it linked to #396?

**Comment by wsbrenk** [comment]
@akasolace i'm not quiet sure. today it happens again with two of my teams which played against 08/15-verlegenheitstruppe teams. maybe it is fixed with the OnlineWorker fix in #396, but i remember another stack trace than this one.

**Comment by akasolace** [comment]
what does it means '08/15-verlegenheitstruppe teams' ?

**Comment by akasolace** [comment]
could you check the bug still exist with last artefacts: r2650 ?

**Comment by wsbrenk** [comment]
> what does it means '08/15-verlegenheitstruppe teams' ?

Footballeurs de rue

>could you check the bug still exist with last artefacts: r2650 ?

i will do that!

**Comment by wsbrenk** [comment]
@akasolace starting r2650 gives the npe isOldie from https://github.com/akasolace/HO/issues/396#issuecomment-592394478 for the teams that had the footballeurs matches;-(

**Comment by akasolace** [comment]
ok, so if I understand correctly
for match against Footballeurs de rue , the function isOldie in module src/main/java/core/model/match/MatchStatistics.java  raises a NPE error ?

so this is another new bug for which fixes should also be ported to 2.2 ? I mean is it a bug only on dev version or also affecting 2.1 ?  Do you know what causes it? It is strange because that function is very old, no?

**Comment by wsbrenk** [comment]
i saw it only in ho 3.0 versions

**Comment by wsbrenk** [comment]
@akasolace i have to check whether the npe of r2650 were the consequence of an error in the previous dev-version which had to download the footballeurs-matches (teamid < 0). i think the isOldie npe had the reason that no team was found in database when initializing the trainings plan.

so in a test this evening i  will try to download the negativ team ids with r2650 and then check if again npes will rise on further ho starts.

**Comment by akasolace** [comment]
@wsbrenk, to be frank, I did not follow all this closely so it is not clear to me.
What I get so far, is that the bug does not exist in 2.x branch, it was introduced in 3.x branch:
     - has the bug been identified already ?
      - do we know which commit introduced the bug ?
     - is it fixed now on dev branch and only user who used dev version at some point might have corrupted database?  => do we need a fix only for those user ?

Thanks in advance for the additional information you can provide.

**Comment by wsbrenk** [comment]
have just successfully carried out the promised test.
- Database reset to date 1.3. (before match against footballeur)
- download matches
- restart HO without any NPE

yesterday the download was made by the previous 3.0 dev-version. So i think the "verlegenheit"-commit really fixes the isOldie NPE which is only relevant for dev 3.0 versions.

i'm still not sure what's about the ArrayIndex-Exception of this ticket. maybe it is also a follow-up the other errors.

**Comment by akasolace** [comment]
@wsbrenk  I will let you decide whether or not we should close this issue but it seems like we can't reproduce it.

**Comment by wsbrenk** [comment]
you're right - i didn't see this error again
