### ISSUE TITLE
[BUG] Can't see what is written behind frame

### ISSUE THREAD

**Issue by siweq86** [akasolace/HO#699]
**Describe the bug**
I can't see what is written behind "frame".

**To Reproduce**
1. Open Hattrick Organizer 3.0
2. Click on 'Squad'
3. Pick a footballer
4. Click "Best position"

**Screenshots**
[]https://i.imgur.com/VQMvz7P.png

**Platform information:**
 - OS: Windows 10
 - HO Version 3.000

**Comment by akasolace** [comment]
@siweq86 can you please put a screenshot to help visualize the issue ... thank you !

**Comment by siweq86** [comment]
Done

**Comment by tychobrailleur** [comment]
Hi @siweq86, I still don't get the issue: you seem to be showing the “Best Position” dropdown, which does hide table content until you have picked the correct position – is that your issue?  

<img width="617" alt="Screenshot 2020-09-21 at 17 59 02" src="https://user-images.githubusercontent.com/114285/93797498-3f605c00-fc34-11ea-9a57-7fafea843c2a.png">

**Comment by akasolace** [comment]
@tychobrailleur on his screenshot, it seems the lines are truncated ... is that the issue @siweq86 ?

**Comment by siweq86** [comment]
Yes, that's true. Shame to admit but for the first time since i'm using HO i noticed that u can resize these windows and then this dropdown works correctly.

[]https://i.imgur.com/1mzE39p.png(url)
[]https://i.imgur.com/zZ3yUrh.png(url)

That's what i meant. So maybe it's not really a bug.

**Comment by akasolace** [comment]
ok I close the issue then
